# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.define 'SLNGINXWEB02' do |node|
    node.vm.box = 'centos/7'
    node.vm.hostname = 'SLNGINXWEB02'

    node.vm.network :private_network, ip:  '192.17.0.5'
    node.vm.network :forwarded_port, guest: 22, host:  '10175', id: "ssh"

    node.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", '256']
      v.customize ["modifyvm", :id, "--name", 'SLNGINXWEB02']
    end
  end
end
