- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: ensure local user has a matching account on the host
      user:
        state: present
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/bash
        groups: sudo
      register: user

    - name: ensure local user's public key is on the host
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
