- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: ensure node apt repository is installed from nodesource
      apt_repository:
        repo: deb https://deb.nodesource.com/node_5.x trusty main
        state: present

    - name: ensure node gpg key is installed from deb.nodesource.com
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: ensure ruby "brightbox" apt repository is installed from launchpad
      apt_repository:
        repo: ppa:brightbox/ruby-ng
        state: present

    - name: ensure apt cache is updated
      apt:
        update_cache: yes

    - name: ensure nodejs is installed
      apt:
        name: nodejs
        state: latest
        update_cache: yes

    - name: ensure ruby2.3 is installed
      apt:
        name: ruby2.3
        state: latest

    - name: ensure nginx is installed
      apt:
        name: nginx
        state: latest
