- hosts: all
  tasks:
    - name: ensure ruby "brightbox" apt repository is installed from launchpad
      apt_repository:

    - name: ensure node apt repository is installed from nodesource
      apt_repository:

    - name: ensure node gpg key is installed from deb.nodesource.com
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: ensure apt cache is updated
      apt:

    - name: ensure nodejs is installed
      apt:

    - name: ensure ruby2.3 is installed
      apt:

    - name: ensure nginx is installed
      apt:
